// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// rejupdate
int rejupdate(LogicalMatrix& rejmat, NumericMatrix const& diffmat, double const& c);
RcppExport SEXP _rankconf_rejupdate(SEXP rejmatSEXP, SEXP diffmatSEXP, SEXP cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< LogicalMatrix& >::type rejmat(rejmatSEXP);
    Rcpp::traits::input_parameter< NumericMatrix const& >::type diffmat(diffmatSEXP);
    Rcpp::traits::input_parameter< double const& >::type c(cSEXP);
    rcpp_result_gen = Rcpp::wrap(rejupdate(rejmat, diffmat, c));
    return rcpp_result_gen;
END_RCPP
}
// indupdate
void indupdate(LogicalMatrix const& rejmat, LogicalMatrix& indmat, NumericMatrix const& diffmat, double const c, int const k);
RcppExport SEXP _rankconf_indupdate(SEXP rejmatSEXP, SEXP indmatSEXP, SEXP diffmatSEXP, SEXP cSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< LogicalMatrix const& >::type rejmat(rejmatSEXP);
    Rcpp::traits::input_parameter< LogicalMatrix& >::type indmat(indmatSEXP);
    Rcpp::traits::input_parameter< NumericMatrix const& >::type diffmat(diffmatSEXP);
    Rcpp::traits::input_parameter< double const >::type c(cSEXP);
    Rcpp::traits::input_parameter< int const >::type k(kSEXP);
    indupdate(rejmat, indmat, diffmat, c, k);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rankconf_rejupdate", (DL_FUNC) &_rankconf_rejupdate, 3},
    {"_rankconf_indupdate", (DL_FUNC) &_rankconf_indupdate, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_rankconf(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
