# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Update the symmetric rejection matrix in place based on what values of
#' the difference matrix are greater than the provided critical value.
#' @param rejmat The rejection matrix
#' @param diffmat The difference matrix
#' @param c A constant
rejupdate <- function(rejmat, diffmat, c) {
    .Call(`_rankconf_rejupdate`, rejmat, diffmat, c)
}

#' Update sampling indicator matrix, in place modifications
#' @param rejmat The rejection matrix
#' @param sigmat The sample indicator matrix
#' @param diffmat The difference matrix
#' @param c The constant for checking already-rejected values
#' @param numind Size of the sample
#' @param k The k in k-FWER
sigupdate <- function(rejmat, sigmat, diffmat, c, numind, k) {
    .Call(`_rankconf_sigupdate`, rejmat, sigmat, diffmat, c, numind, k)
}

#' Returns the kth largest value by sorting in place
#' @param x Numeric vector.
#' @param k Specifies the kth largest value.
kmax <- function(x, k) {
    .Call(`_rankconf_kmax`, x, k)
}

